language: python
dist: xenial
sudo: false

script:
- echo build

deploy:
  - skip_cleanup: true
    provider: script
    script: echo deploying my app 

after_deploy:
  - git clone https://github.com/searchmetrics/dd-deploy-metric.git ; bash dd-deploy-metric/dd-deploy-metric.sh

